version: '3'

services:
    pihole-unbound:
        hostname: ${HOSTNAME}
        container_name: pihole-unbound
        build: .
        image: simc/pihole-unbound
        ports:
            - 443:443/tcp
            - 53:53/tcp
            - 53:53/udp
            - 80:80/tcp
            - 67:67/udp
        environment:
            ServerIP: ${ServerIP}
            TZ: ${TZ}
            WEBPASSWORD: ${WEBPASSWORD}
            REV_SERVER: ${REV_SERVER}
            REV_SERVER_TARGET: ${REV_SERVER_TARGET}
            REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
            REV_SERVER_CIDR: ${REV_SERVER_CIDR}
            DNS1: 127.0.0.1#5335 # Hardcoded to our Unbound server
            DNS2: 127.0.0.1#5335 # Hardcoded to our Unbound server
            DNSSEC: "true" # Enable DNSSEC
        volumes:
            - ./etc-pihole:/etc/pihole:rw
            - ./etc-dnsmasq.d:/etc/dnsmasq.d:rw 
        network_mode: host
        cap_add:
            - NET_ADMIN
        restart: ${RESTART}
 

